# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MaHDTUI2oLZglrb70L0TqzxOD0E4FH1Z
"""

def chatbot():
    print("Chatbot started. Type 'bye' to exit.")

    while True:
        user = input("You: ").lower()

        # Greeting responses
        if user in ["hi", "hello", "hey", "hii", "hallo"]:
            print("Bot: Hello!")

        # Exit responses
        elif user in ["bye", "exit", "quit", "close"]:
            print("Bot: Goodbye!")
            break

        # Default fallback
        else:
            print("Bot: Sorry, I don't know the answer to this.")

chatbot()

